// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: skill_service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkillService_AddSkillToUser_FullMethodName      = "/skill.SkillService/AddSkillToUser"
	SkillService_RemoveSkillFromUser_FullMethodName = "/skill.SkillService/RemoveSkillFromUser"
	SkillService_GetSkillsByUser_FullMethodName     = "/skill.SkillService/GetSkillsByUser"
	SkillService_GetAllSkills_FullMethodName        = "/skill.SkillService/GetAllSkills"
)

// SkillServiceClient is the client API for SkillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The SkillService definition
type SkillServiceClient interface {
	AddSkillToUser(ctx context.Context, in *AddSkillRequest, opts ...grpc.CallOption) (*Skill, error)
	RemoveSkillFromUser(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSkillsByUser(ctx context.Context, in *GetSkillsByUserRequest, opts ...grpc.CallOption) (*SkillList, error)
	GetAllSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SkillList, error)
}

type skillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillServiceClient(cc grpc.ClientConnInterface) SkillServiceClient {
	return &skillServiceClient{cc}
}

func (c *skillServiceClient) AddSkillToUser(ctx context.Context, in *AddSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Skill)
	err := c.cc.Invoke(ctx, SkillService_AddSkillToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) RemoveSkillFromUser(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SkillService_RemoveSkillFromUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetSkillsByUser(ctx context.Context, in *GetSkillsByUserRequest, opts ...grpc.CallOption) (*SkillList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillList)
	err := c.cc.Invoke(ctx, SkillService_GetSkillsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetAllSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SkillList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SkillList)
	err := c.cc.Invoke(ctx, SkillService_GetAllSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillServiceServer is the server API for SkillService service.
// All implementations must embed UnimplementedSkillServiceServer
// for forward compatibility.
//
// The SkillService definition
type SkillServiceServer interface {
	AddSkillToUser(context.Context, *AddSkillRequest) (*Skill, error)
	RemoveSkillFromUser(context.Context, *RemoveSkillRequest) (*Empty, error)
	GetSkillsByUser(context.Context, *GetSkillsByUserRequest) (*SkillList, error)
	GetAllSkills(context.Context, *Empty) (*SkillList, error)
	mustEmbedUnimplementedSkillServiceServer()
}

// UnimplementedSkillServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkillServiceServer struct{}

func (UnimplementedSkillServiceServer) AddSkillToUser(context.Context, *AddSkillRequest) (*Skill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSkillToUser not implemented")
}
func (UnimplementedSkillServiceServer) RemoveSkillFromUser(context.Context, *RemoveSkillRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSkillFromUser not implemented")
}
func (UnimplementedSkillServiceServer) GetSkillsByUser(context.Context, *GetSkillsByUserRequest) (*SkillList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkillsByUser not implemented")
}
func (UnimplementedSkillServiceServer) GetAllSkills(context.Context, *Empty) (*SkillList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSkills not implemented")
}
func (UnimplementedSkillServiceServer) mustEmbedUnimplementedSkillServiceServer() {}
func (UnimplementedSkillServiceServer) testEmbeddedByValue()                      {}

// UnsafeSkillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillServiceServer will
// result in compilation errors.
type UnsafeSkillServiceServer interface {
	mustEmbedUnimplementedSkillServiceServer()
}

func RegisterSkillServiceServer(s grpc.ServiceRegistrar, srv SkillServiceServer) {
	// If the following call pancis, it indicates UnimplementedSkillServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkillService_ServiceDesc, srv)
}

func _SkillService_AddSkillToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).AddSkillToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_AddSkillToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).AddSkillToUser(ctx, req.(*AddSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_RemoveSkillFromUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).RemoveSkillFromUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_RemoveSkillFromUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).RemoveSkillFromUser(ctx, req.(*RemoveSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetSkillsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetSkillsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetSkillsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetSkillsByUser(ctx, req.(*GetSkillsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetAllSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetAllSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillService_GetAllSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetAllSkills(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillService_ServiceDesc is the grpc.ServiceDesc for SkillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skill.SkillService",
	HandlerType: (*SkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSkillToUser",
			Handler:    _SkillService_AddSkillToUser_Handler,
		},
		{
			MethodName: "RemoveSkillFromUser",
			Handler:    _SkillService_RemoveSkillFromUser_Handler,
		},
		{
			MethodName: "GetSkillsByUser",
			Handler:    _SkillService_GetSkillsByUser_Handler,
		},
		{
			MethodName: "GetAllSkills",
			Handler:    _SkillService_GetAllSkills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skill_service.proto",
}
