// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: skill_service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single skill
type Skill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Skill) Reset() {
	*x = Skill{}
	mi := &file_skill_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_skill_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_skill_service_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Skill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Skill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Request to add a skill to a user
type AddSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Skill         *Skill                 `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"` // The skill to add
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSkillRequest) Reset() {
	*x = AddSkillRequest{}
	mi := &file_skill_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSkillRequest) ProtoMessage() {}

func (x *AddSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSkillRequest.ProtoReflect.Descriptor instead.
func (*AddSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddSkillRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddSkillRequest) GetSkill() *Skill {
	if x != nil {
		return x.Skill
	}
	return nil
}

// Request to remove a skill from a user
type RemoveSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkillId       string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"` // The ID of the skill to remove
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSkillRequest) Reset() {
	*x = RemoveSkillRequest{}
	mi := &file_skill_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkillRequest) ProtoMessage() {}

func (x *RemoveSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkillRequest.ProtoReflect.Descriptor instead.
func (*RemoveSkillRequest) Descriptor() ([]byte, []int) {
	return file_skill_service_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveSkillRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveSkillRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

// Request to get skills for a specific user
type GetSkillsByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillsByUserRequest) Reset() {
	*x = GetSkillsByUserRequest{}
	mi := &file_skill_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillsByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillsByUserRequest) ProtoMessage() {}

func (x *GetSkillsByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skill_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillsByUserRequest.ProtoReflect.Descriptor instead.
func (*GetSkillsByUserRequest) Descriptor() ([]byte, []int) {
	return file_skill_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSkillsByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// A list of skills
type SkillList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*Skill               `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillList) Reset() {
	*x = SkillList{}
	mi := &file_skill_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillList) ProtoMessage() {}

func (x *SkillList) ProtoReflect() protoreflect.Message {
	mi := &file_skill_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillList.ProtoReflect.Descriptor instead.
func (*SkillList) Descriptor() ([]byte, []int) {
	return file_skill_service_proto_rawDescGZIP(), []int{4}
}

func (x *SkillList) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

// A generic empty message for methods that don't return any specific data
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_skill_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_skill_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_skill_service_proto_rawDescGZIP(), []int{5}
}

var File_skill_service_proto protoreflect.FileDescriptor

const file_skill_service_proto_rawDesc = "" +
	"\n" +
	"\x13skill_service.proto\x12\x05skill\"M\n" +
	"\x05Skill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"N\n" +
	"\x0fAddSkillRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\"\n" +
	"\x05skill\x18\x02 \x01(\v2\f.skill.SkillR\x05skill\"H\n" +
	"\x12RemoveSkillRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\"1\n" +
	"\x16GetSkillsByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\tSkillList\x12$\n" +
	"\x06skills\x18\x01 \x03(\v2\f.skill.SkillR\x06skills\"\a\n" +
	"\x05Empty2\xfa\x01\n" +
	"\fSkillService\x126\n" +
	"\x0eAddSkillToUser\x12\x16.skill.AddSkillRequest\x1a\f.skill.Skill\x12>\n" +
	"\x13RemoveSkillFromUser\x12\x19.skill.RemoveSkillRequest\x1a\f.skill.Empty\x12B\n" +
	"\x0fGetSkillsByUser\x12\x1d.skill.GetSkillsByUserRequest\x1a\x10.skill.SkillList\x12.\n" +
	"\fGetAllSkills\x12\f.skill.Empty\x1a\x10.skill.SkillListB\x03Z\x01.b\x06proto3"

var (
	file_skill_service_proto_rawDescOnce sync.Once
	file_skill_service_proto_rawDescData []byte
)

func file_skill_service_proto_rawDescGZIP() []byte {
	file_skill_service_proto_rawDescOnce.Do(func() {
		file_skill_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skill_service_proto_rawDesc), len(file_skill_service_proto_rawDesc)))
	})
	return file_skill_service_proto_rawDescData
}

var file_skill_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_skill_service_proto_goTypes = []any{
	(*Skill)(nil),                  // 0: skill.Skill
	(*AddSkillRequest)(nil),        // 1: skill.AddSkillRequest
	(*RemoveSkillRequest)(nil),     // 2: skill.RemoveSkillRequest
	(*GetSkillsByUserRequest)(nil), // 3: skill.GetSkillsByUserRequest
	(*SkillList)(nil),              // 4: skill.SkillList
	(*Empty)(nil),                  // 5: skill.Empty
}
var file_skill_service_proto_depIdxs = []int32{
	0, // 0: skill.AddSkillRequest.skill:type_name -> skill.Skill
	0, // 1: skill.SkillList.skills:type_name -> skill.Skill
	1, // 2: skill.SkillService.AddSkillToUser:input_type -> skill.AddSkillRequest
	2, // 3: skill.SkillService.RemoveSkillFromUser:input_type -> skill.RemoveSkillRequest
	3, // 4: skill.SkillService.GetSkillsByUser:input_type -> skill.GetSkillsByUserRequest
	5, // 5: skill.SkillService.GetAllSkills:input_type -> skill.Empty
	0, // 6: skill.SkillService.AddSkillToUser:output_type -> skill.Skill
	5, // 7: skill.SkillService.RemoveSkillFromUser:output_type -> skill.Empty
	4, // 8: skill.SkillService.GetSkillsByUser:output_type -> skill.SkillList
	4, // 9: skill.SkillService.GetAllSkills:output_type -> skill.SkillList
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_skill_service_proto_init() }
func file_skill_service_proto_init() {
	if File_skill_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skill_service_proto_rawDesc), len(file_skill_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skill_service_proto_goTypes,
		DependencyIndexes: file_skill_service_proto_depIdxs,
		MessageInfos:      file_skill_service_proto_msgTypes,
	}.Build()
	File_skill_service_proto = out.File
	file_skill_service_proto_goTypes = nil
	file_skill_service_proto_depIdxs = nil
}
