# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x04user\"H\n\x0bUserProfile\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x62io\x18\x03 \x01(\t\x12\x12\n\navatar_url\x18\x04 \x01(\t\"U\n\x18\x43reateUserProfileRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x62io\x18\x03 \x01(\t\x12\x12\n\navatar_url\x18\x04 \x01(\t\"U\n\x18UpdateUserProfileRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x62io\x18\x03 \x01(\t\x12\x12\n\navatar_url\x18\x04 \x01(\t\"#\n\x15GetUserProfileRequest\x12\n\n\x02id\x18\x01 \x01(\t2\xdf\x01\n\x0bUserService\x12\x46\n\x11\x43reateUserProfile\x12\x1e.user.CreateUserProfileRequest\x1a\x11.user.UserProfile\x12\x46\n\x11UpdateUserProfile\x12\x1e.user.UpdateUserProfileRequest\x1a\x11.user.UserProfile\x12@\n\x0eGetUserProfile\x12\x1b.user.GetUserProfileRequest\x1a\x11.user.UserProfileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERPROFILE']._serialized_start=28
  _globals['_USERPROFILE']._serialized_end=100
  _globals['_CREATEUSERPROFILEREQUEST']._serialized_start=102
  _globals['_CREATEUSERPROFILEREQUEST']._serialized_end=187
  _globals['_UPDATEUSERPROFILEREQUEST']._serialized_start=189
  _globals['_UPDATEUSERPROFILEREQUEST']._serialized_end=274
  _globals['_GETUSERPROFILEREQUEST']._serialized_start=276
  _globals['_GETUSERPROFILEREQUEST']._serialized_end=311
  _globals['_USERSERVICE']._serialized_start=314
  _globals['_USERSERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
