// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v6.31.0
// source: skill_service.proto

package skills

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SkillServiceClient is the client API for SkillService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SkillServiceClient interface {
	AddSkillToUser(ctx context.Context, in *AddSkillRequest, opts ...grpc.CallOption) (*Skill, error)
	RemoveSkillFromUser(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*Empty, error)
	GetSkillsByUser(ctx context.Context, in *GetSkillsByUserRequest, opts ...grpc.CallOption) (*SkillList, error)
	GetAllSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SkillList, error)
}

type skillServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillServiceClient(cc grpc.ClientConnInterface) SkillServiceClient {
	return &skillServiceClient{cc}
}

func (c *skillServiceClient) AddSkillToUser(ctx context.Context, in *AddSkillRequest, opts ...grpc.CallOption) (*Skill, error) {
	out := new(Skill)
	err := c.cc.Invoke(ctx, "/skills.SkillService/AddSkillToUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) RemoveSkillFromUser(ctx context.Context, in *RemoveSkillRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/skills.SkillService/RemoveSkillFromUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetSkillsByUser(ctx context.Context, in *GetSkillsByUserRequest, opts ...grpc.CallOption) (*SkillList, error) {
	out := new(SkillList)
	err := c.cc.Invoke(ctx, "/skills.SkillService/GetSkillsByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *skillServiceClient) GetAllSkills(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SkillList, error) {
	out := new(SkillList)
	err := c.cc.Invoke(ctx, "/skills.SkillService/GetAllSkills", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillServiceServer is the server API for SkillService service.
// All implementations must embed UnimplementedSkillServiceServer
// for forward compatibility
type SkillServiceServer interface {
	AddSkillToUser(context.Context, *AddSkillRequest) (*Skill, error)
	RemoveSkillFromUser(context.Context, *RemoveSkillRequest) (*Empty, error)
	GetSkillsByUser(context.Context, *GetSkillsByUserRequest) (*SkillList, error)
	GetAllSkills(context.Context, *Empty) (*SkillList, error)
	mustEmbedUnimplementedSkillServiceServer()
}

// UnimplementedSkillServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSkillServiceServer struct {
}

func (UnimplementedSkillServiceServer) AddSkillToUser(context.Context, *AddSkillRequest) (*Skill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSkillToUser not implemented")
}
func (UnimplementedSkillServiceServer) RemoveSkillFromUser(context.Context, *RemoveSkillRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSkillFromUser not implemented")
}
func (UnimplementedSkillServiceServer) GetSkillsByUser(context.Context, *GetSkillsByUserRequest) (*SkillList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSkillsByUser not implemented")
}
func (UnimplementedSkillServiceServer) GetAllSkills(context.Context, *Empty) (*SkillList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllSkills not implemented")
}
func (UnimplementedSkillServiceServer) mustEmbedUnimplementedSkillServiceServer() {}

// UnsafeSkillServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillServiceServer will
// result in compilation errors.
type UnsafeSkillServiceServer interface {
	mustEmbedUnimplementedSkillServiceServer()
}

func RegisterSkillServiceServer(s grpc.ServiceRegistrar, srv SkillServiceServer) {
	s.RegisterService(&SkillService_ServiceDesc, srv)
}

func _SkillService_AddSkillToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).AddSkillToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skills.SkillService/AddSkillToUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).AddSkillToUser(ctx, req.(*AddSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_RemoveSkillFromUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).RemoveSkillFromUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skills.SkillService/RemoveSkillFromUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).RemoveSkillFromUser(ctx, req.(*RemoveSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetSkillsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetSkillsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skills.SkillService/GetSkillsByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetSkillsByUser(ctx, req.(*GetSkillsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SkillService_GetAllSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillServiceServer).GetAllSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skills.SkillService/GetAllSkills",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillServiceServer).GetAllSkills(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillService_ServiceDesc is the grpc.ServiceDesc for SkillService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skills.SkillService",
	HandlerType: (*SkillServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSkillToUser",
			Handler:    _SkillService_AddSkillToUser_Handler,
		},
		{
			MethodName: "RemoveSkillFromUser",
			Handler:    _SkillService_RemoveSkillFromUser_Handler,
		},
		{
			MethodName: "GetSkillsByUser",
			Handler:    _SkillService_GetSkillsByUser_Handler,
		},
		{
			MethodName: "GetAllSkills",
			Handler:    _SkillService_GetAllSkills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "skill_service.proto",
}
